# Site settings
title: BrunoScience
email: MarkBruns@MarkBruns.com
description: What's wrong with Science ... but, more importantly, how should we fix it?
twitter_username: MarkBruns
github_username:  BRUNOSolutions

# Build settings
markdown: kramdown
