# Site settings
title: BrunoScience
email: QualityFellow@gmail.com
description: The best that we can hope to achieve in science is simply to misunderstand at a deeper level.
twitter_username: QualityFellow
github_username:  BRUNOScience

# Build settings
markdown: kramdown
