# Site settings
title: BrunoScience
email: MarkBruns@MarkBruns.com
description: What's wrong with Science ... but, more importantly, what can we do to fix it?
twitter_username: MarkBruns
github_username:  BRUNOScience

# Build settings
markdown: kramdown
