# Site settings
title: BrunoScience
email: MarkBruns@MarkBruns.com
description: What's wrong with Science ... but, more importantly, what must we do to fix it?
twitter_username: QualityFellow
github_username:  BRUNOScience

# Build settings
markdown: kramdown
